allprojects { p -> afterEvaluate {
    if (!p.plugins.hasPlugin('net.minecraftforge.gradle')) return
    p.minecraft.runs.gameTestServer {
        workingDirectory p.file(p.findProperty('cod3TestRun') ?: 'build/cod3-gametest')
        property 'forge.logging.console.level', 'info'
        property 'forge.enabledGameTestNamespaces', p.findProperty('cod3Namespaces') ?: 'dynasty_cod3'
        jvmArgs '-Xmx'+(p.findProperty('cod3TestHeap') ?: '1024m'), '-XX:ActiveProcessorCount=2'
    }
} }
