allprojects { p -> afterEvaluate {
    if (!p.plugins.hasPlugin('net.minecraftforge.gradle')) return
    p.minecraft.runs.gameTestServer {
        workingDirectory p.file('build/cod4-gametest')
        property 'forge.logging.console.level', 'info'
        property 'forge.enabledGameTestNamespaces', p.hasProperty('cod4Regression') ? 'dynasty,dynasty_cod4,dynasty_infusion' : 'dynasty_cod4'
    }
} }
