package com.dynasty;

import java.util.List;

/**
 * 图鉴·全部表驱动饰品（gen_trinkets3/4/5 共 130 件）。
 *
 * ⚠ 本文件由 tools/art/gen_codex_all.py 生成，不要手改 —— 改生成器（或饰品表）再重跑，
 *   这样「配方材料 / 属性 / 效果 / 命中触发 / 连携组」永远和表一致。
 *   与 DynastyCodexGear3 重复的 id 由 DynastyCodex.all() 去重（先登记的优先）。
 *
 * Generated codex entries for every table-driven accessory; edit the generator, not this file.
 */
final class DynastyCodexAll {

    private DynastyCodexAll() {
    }

    private static void entry(List<DynastyCodex.Entry> l, String id, String zhSource, String enSource,
                              String zhUse, String enUse, String... ingredients) {
        l.add(new DynastyCodex.Entry(id, zhSource, enSource, zhUse, enUse, ingredients));
    }

    static void add(List<DynastyCodex.Entry> l) {
        entry(l, "abyss_pearl",
                "合成：混元珠 + 避水珠 + 朱砂",
                "Craft: Hunyuan Pearl + Water-Repelling Pearl + Cinnabar",
                "深渊珠：夜晚：攻击 +35%、击退 +0.4、命中 50% 会心（30% 概率）、连携·幽冥献祭。",
                "Abyss Pearl: attack +35%, attack knockback +0.4 (at night), 50% critical on hit (30% chance), synergy: Underworld Sacrifice.",
                "dynasty:hunyuan_pearl", "dynasty:sea_pearl", "dynasty:cinnabar");
        entry(l, "alchemy_furnace_charm",
                "合成：朱砂 + 符纸 + 金币",
                "Craft: Cinnabar + Talisman Paper + Gold Coin",
                "丹炉坠：生命 +260、常驻再生 I。",
                "Alchemy Furnace Charm: health +260, permanent Regeneration I.",
                "dynasty:cinnabar", "dynasty:talisman_paper", "dynasty:gold_coin");
        entry(l, "alchemy_pendant",
                "合成：朱砂 + 长生丹",
                "Craft: Cinnabar + Immortality Pill",
                "炼丹坠：生命 +200、常驻再生 II。",
                "Alchemy Pendant: health +200, permanent Regeneration II.",
                "dynasty:cinnabar", "dynasty:pill_longevity");
        entry(l, "armor_piercer_token",
                "合成：精钢 + 龙晶 + 朱砂",
                "Craft: Refined Steel + Dragon Crystal + Cinnabar",
                "破甲符牌：攻击 +16%、击退 +0.35。",
                "Armour-Piercer Token: attack +16%, attack knockback +0.35.",
                "dynasty:refined_steel", "dynasty:dragon_crystal", "dynasty:cinnabar");
        entry(l, "arrow_quiver",
                "合成：minecraft:leather + 丝绸 + minecraft:arrow",
                "Craft: minecraft:leather + Silk + minecraft:arrow",
                "箭囊：攻击 +8%、移速 +4%。",
                "Arrow Quiver: attack +8%, movement speed +4%.",
                "minecraft:leather", "dynasty:silk", "minecraft:arrow");
        entry(l, "bagua_mirror",
                "合成：铜镜 + 朱砂 + 玉",
                "Craft: Bronze Mirror + Cinnabar + Jade",
                "八卦镜：护甲 +14、常驻抗性 I。",
                "Bagua Mirror: armour +14, permanent Resistance I.",
                "dynasty:bronze_mirror", "dynasty:cinnabar", "dynasty:jade");
        entry(l, "bear_paw",
                "合成：minecraft:leather + 精钢",
                "Craft: minecraft:leather + Refined Steel",
                "熊掌：生命 +300、攻击 +8%。",
                "Bear Paw: health +300, attack +8%.",
                "minecraft:leather", "dynasty:refined_steel");
        entry(l, "belt_buckle",
                "合成：青铜锭 + 银锭",
                "Craft: Bronze Ingot + Silver Ingot",
                "腰带扣：护甲 +6、生命 +120。",
                "Belt Buckle: armour +6, health +120.",
                "dynasty:bronze_ingot", "dynasty:silver_ingot");
        entry(l, "blood_iron_sash",
                "合成：精钢 + 龙鳞 + 丝绸",
                "Craft: Refined Steel + Dragon Scale + Silk",
                "血铁腰带：生命上限 -15%、护甲 +18、连携·生死代价。",
                "Blood Iron Sash: max health -15%, armour +18, synergy: Life for Power.",
                "dynasty:refined_steel", "dynasty:dragon_scale", "dynasty:silk");
        entry(l, "blood_oath_seal",
                "合成：朱砂 + 龙晶 + 金币",
                "Craft: Cinnabar + Dragon Crystal + Gold Coin",
                "血誓印：生命上限 -30%、攻击 +35%、命中吸血 15%、连携·生死代价。",
                "Blood Oath Seal: max health -30%, attack +35%, 15% lifesteal on hit, synergy: Life for Power.",
                "dynasty:cinnabar", "dynasty:dragon_crystal", "dynasty:gold_coin");
        entry(l, "bone_chill_pendant",
                "合成：帝骸骨 + 避水珠 + 玉",
                "Craft: Emperor's Bone + Water-Repelling Pearl + Jade",
                "寒骨佩：水下：攻击 +25%、常驻内伤 II、命中附加 45 点雷罚（35% 概率）、连携·幽冥献祭。",
                "Bone Chill Pendant: attack +25% (underwater), permanent Internal Injury II, 45 extra thunder damage on hit (35% chance), synergy: Underworld Sacrifice.",
                "dynasty:emperor_bone", "dynasty:sea_pearl", "dynasty:jade");
        entry(l, "bone_reaper_tally",
                "合成：帝骸骨 + 竹简 + 朱砂",
                "Craft: Emperor's Bone + Bamboo Slip + Cinnabar",
                "白骨算筹：生命上限 -20%、攻击 +25%、常驻：击退 +0.5、命中斩杀 20% 血线以下的目标、连携·生死代价。",
                "Bone Reaper Tally: max health -20%, attack +25%, attack knockback +0.5 (always), executes below 20% health, synergy: Life for Power.",
                "dynasty:emperor_bone", "dynasty:bamboo_slip", "dynasty:cinnabar");
        entry(l, "bow_string",
                "合成：丝绸 + minecraft:string + 精钢",
                "Craft: Silk + minecraft:string + Refined Steel",
                "弓弦护腕：攻速 +12%、攻击 +5%。",
                "Bowstring Bracer: attack speed +12%, attack +5%.",
                "dynasty:silk", "minecraft:string", "dynasty:refined_steel");
        entry(l, "brush_rack",
                "合成：毛笔 + 玉 + 青铜锭",
                "Craft: Ink Brush + Jade + Bronze Ingot",
                "笔架坠：攻速 +14%、攻击 +6%。",
                "Brush Rack Charm: attack speed +14%, attack +6%.",
                "dynasty:ink_brush", "dynasty:jade", "dynasty:bronze_ingot");
        entry(l, "candle_of_the_dead",
                "合成：帝骸骨 + 符纸 + 朱砂",
                "Craft: Emperor's Bone + Talisman Paper + Cinnabar",
                "亡者烛：夜晚：攻击 +30%、白天：生命 -150、连携·幽冥献祭。",
                "Candle of the Dead: attack +30% (at night), health -150 (in daylight), synergy: Underworld Sacrifice.",
                "dynasty:emperor_bone", "dynasty:talisman_paper", "dynasty:cinnabar");
        entry(l, "cavalry_sash",
                "合成：丝绸 + 精钢 + 龙鳞",
                "Craft: Silk + Refined Steel + Dragon Scale",
                "铁骑带：骑乘：攻击 +15%、移速 +10%、连携·巧匠边塞。",
                "Cavalry Sash: attack +15%, movement speed +10% (while mounted), synergy: Frontier Craft.",
                "dynasty:silk", "dynasty:refined_steel", "dynasty:dragon_scale");
        entry(l, "cloud_pattern",
                "合成：云锦囊 + 玉 + 丝绸",
                "Craft: Cloud Pouch + Jade + Silk",
                "云纹佩：移速 +12%、抗击退 +0.3。",
                "Cloud Pattern Charm: movement speed +12%, knockback resistance +0.3.",
                "dynasty:cloud_brocade", "dynasty:jade", "dynasty:silk");
        entry(l, "conch_horn",
                "合成：海螺 + 丝绸",
                "Craft: Sea Conch + Silk",
                "海螺号：生命 +240、移速 +8%。",
                "Conch Horn: health +240, movement speed +8%.",
                "dynasty:sea_conch", "dynasty:silk");
        entry(l, "crane_feather",
                "合成：凤凰羽 + 丝绸",
                "Craft: Phoenix Feather + Silk",
                "鹤羽：移速 +10%、常驻缓降 I。",
                "Crane Feather: movement speed +10%, permanent Slow Falling I.",
                "dynasty:phoenix_feather", "dynasty:silk");
        entry(l, "crimson_pact_charm",
                "合成：混元珠 + 朱砂 + 金币",
                "Craft: Hunyuan Pearl + Cinnabar + Gold Coin",
                "血契坠：生命上限 -40%、攻击 +50%、命中吸血 20%（60% 概率）、连携·生死代价。",
                "Crimson Pact Charm: max health -40%, attack +50%, 20% lifesteal on hit (60% chance), synergy: Life for Power.",
                "dynasty:hunyuan_pearl", "dynasty:cinnabar", "dynasty:gold_coin");
        entry(l, "dawn_blade_charm",
                "合成：精钢 + 丝绸 + 金币",
                "Craft: Refined Steel + Silk + Gold Coin",
                "破晓刃坠：白天：攻击 +22%、夜晚：移速 +10%、命中满血目标 35%、连携·昼夜双生。",
                "Dawn Blade Charm: attack +22% (in daylight), movement speed +10% (at night), 35% against full-health targets, synergy: Day & Night.",
                "dynasty:refined_steel", "dynasty:silk", "dynasty:gold_coin");
        entry(l, "dawn_drum",
                "合成：金币 + 铜镜 + 丝绸",
                "Craft: Gold Coin + Bronze Mirror + Silk",
                "晨钟坠：白天：攻速 +12%、移速 +8%、连携·昼夜双生。",
                "Dawn Bell Charm: attack speed +12%, movement speed +8% (in daylight), synergy: Day & Night.",
                "dynasty:gold_coin", "dynasty:bronze_mirror", "dynasty:silk");
        entry(l, "deathbed_talisman",
                "合成：符纸 + 帝骸骨 + 朱砂",
                "Craft: Talisman Paper + Emperor's Bone + Cinnabar",
                "榻前符：残血：攻击 +30%、移速 +30%、命中斩杀 25% 血线以下的目标（60% 概率）、连携·生死代价。",
                "Deathbed Talisman: attack +30%, movement speed +30% (at low health), executes below 25% health (60% chance), synergy: Life for Power.",
                "dynasty:talisman_paper", "dynasty:emperor_bone", "dynasty:cinnabar");
        entry(l, "deer_antler",
                "合成：minecraft:bone + 玉",
                "Craft: minecraft:bone + Jade",
                "鹿角：生命 +260、常驻再生 I。",
                "Deer Antler: health +260, permanent Regeneration I.",
                "minecraft:bone", "dynasty:jade");
        entry(l, "disha_talisman",
                "合成：帝骸骨 + 符纸 + 朱砂",
                "Craft: Emperor's Bone + Talisman Paper + Cinnabar",
                "地煞符：护甲 +18、击退 +0.4。",
                "Disha Talisman: armour +18, attack knockback +0.4.",
                "dynasty:emperor_bone", "dynasty:talisman_paper", "dynasty:cinnabar");
        entry(l, "diver_signet",
                "合成：海螺 + 避水珠 + 精钢",
                "Craft: Sea Conch + Water-Repelling Pearl + Refined Steel",
                "潜蛟印：水下：护甲 +20、攻击 +25%、连携·巧匠边塞。",
                "Diver Signet: armour +20, attack +25% (underwater), synergy: Frontier Craft.",
                "dynasty:sea_conch", "dynasty:sea_pearl", "dynasty:refined_steel");
        entry(l, "dragon_blood_pearl",
                "合成：龙晶 + 朱砂 + 金币",
                "Craft: Dragon Crystal + Cinnabar + Gold Coin",
                "龙血珠：生命 +360、攻击 +14%。",
                "Dragon Blood Pearl: health +360, attack +14%.",
                "dynasty:dragon_crystal", "dynasty:cinnabar", "dynasty:gold_coin");
        entry(l, "dragon_robe_sash",
                "合成：龙鳞 + 玉 + 丝绸",
                "Craft: Dragon Scale + Jade + Silk",
                "龙袍玉带：护甲 +14、生命 +200。",
                "Dragon Robe Sash: armour +14, health +200.",
                "dynasty:dragon_scale", "dynasty:jade", "dynasty:silk");
        entry(l, "dragon_scale_sash",
                "合成：龙鳞 + 精钢 + 丝绸",
                "Craft: Dragon Scale + Refined Steel + Silk",
                "龙鳞带：护甲 +16、抗击退 +0.45。",
                "Dragon Scale Sash: armour +16, knockback resistance +0.45.",
                "dynasty:dragon_scale", "dynasty:refined_steel", "dynasty:silk");
        entry(l, "drum_beater",
                "合成：竹简 + 丝绸",
                "Craft: Bamboo Slip + Silk",
                "鼓槌：攻速 +15%、攻击 +5%。",
                "Drum Beater: attack speed +15%, attack +5%.",
                "dynasty:bamboo_slip", "dynasty:silk");
        entry(l, "dusk_raider_badge",
                "合成：精钢 + 丝绸 + 朱砂",
                "Craft: Refined Steel + Silk + Cinnabar",
                "夜袭徽：夜晚：攻击 +20%、移速 +12%、连携·巧匠边塞。",
                "Dusk Raider Badge: attack +20%, movement speed +12% (at night), synergy: Frontier Craft.",
                "dynasty:refined_steel", "dynasty:silk", "dynasty:cinnabar");
        entry(l, "dusk_veil_charm",
                "合成：丝绸 + 徽墨 + 朱砂",
                "Craft: Silk + Ink Stick + Cinnabar",
                "暮色帷幕：夜晚：攻击 +26%、白天：生命上限 -20%、命中 45% 会心（25% 概率）、连携·昼夜双生。",
                "Dusk Veil Charm: attack +26% (at night), max health -20% (in daylight), 45% critical on hit (25% chance), synergy: Day & Night.",
                "dynasty:silk", "dynasty:ink_stick", "dynasty:cinnabar");
        entry(l, "eclipse_bead",
                "合成：避水珠 + 龙晶 + 朱砂",
                "Craft: Water-Repelling Pearl + Dragon Crystal + Cinnabar",
                "蚀月珠：夜晚：攻击 +30%、白天：护甲 -6、命中 55% 会心（20% 概率）、连携·昼夜双生。",
                "Eclipse Bead: attack +30% (at night), armour -6 (in daylight), 55% critical on hit (20% chance), synergy: Day & Night.",
                "dynasty:sea_pearl", "dynasty:dragon_crystal", "dynasty:cinnabar");
        entry(l, "edict_of_dragon",
                "合成：龙帝玉玺 + 金币 + 兵器图纸",
                "Craft: Dragon Emperor's Seal + Gold Coin + Weapon Blueprint",
                "龙威敕令：攻击 +10%、常驻龙威 I、连携·天朝敕令。",
                "Edict of Dragon Might: attack +10%, permanent Dragon Might I, synergy: Imperial Edict.",
                "dynasty:dragon_emperor_seal", "dynasty:gold_coin", "dynasty:blueprint");
        entry(l, "edict_of_dread",
                "合成：白虎牙 + 金币 + 兵器图纸",
                "Craft: White Tiger Fang + Gold Coin + Weapon Blueprint",
                "威慑敕令：攻击 +10%、常驻威慑 I、命中斩杀 10% 血线以下的目标、连携·天朝敕令。",
                "Edict of Dread: attack +10%, permanent Intimidation I, executes below 10% health, synergy: Imperial Edict.",
                "dynasty:baihu_fang", "dynasty:gold_coin", "dynasty:blueprint");
        entry(l, "edict_of_iron",
                "合成：精钢 + 金币 + 兵器图纸",
                "Craft: Refined Steel + Gold Coin + Weapon Blueprint",
                "铁壁敕令：护甲 +8、常驻铁壁 I、连携·天朝敕令。",
                "Edict of Iron Wall: armour +8, permanent Iron Wall I, synergy: Imperial Edict.",
                "dynasty:refined_steel", "dynasty:gold_coin", "dynasty:blueprint");
        entry(l, "edict_of_loyalty",
                "合成：金印 + 金币 + 兵器图纸",
                "Craft: Gold Seal Charm + Gold Coin + Weapon Blueprint",
                "忠诚敕令：生命 +180、常驻忠诚 I、连携·天朝敕令。",
                "Edict of Loyalty: health +180, permanent Loyalty I, synergy: Imperial Edict.",
                "dynasty:gold_seal_charm", "dynasty:gold_coin", "dynasty:blueprint");
        entry(l, "edict_of_mandate",
                "合成：太乙玉 + 金币 + 兵器图纸",
                "Craft: Taiyi Jade + Gold Coin + Weapon Blueprint",
                "天命敕令：幸运 +2、常驻天命 I、连携·天朝敕令。",
                "Edict of Mandate: luck +2, permanent Mandate of Heaven I, synergy: Imperial Edict.",
                "dynasty:taiyi_jade", "dynasty:gold_coin", "dynasty:blueprint");
        entry(l, "edict_of_swift",
                "合成：朱雀羽 + 金币 + 兵器图纸",
                "Craft: Vermilion Feather + Gold Coin + Weapon Blueprint",
                "疾风敕令：移速 +6%、常驻疾风 I、连携·天朝敕令。",
                "Edict of Swift Wind: movement speed +6%, permanent Swift Wind I, synergy: Imperial Edict.",
                "dynasty:zhuque_feather", "dynasty:gold_coin", "dynasty:blueprint");
        entry(l, "flesh_gamble_dice",
                "合成：帝骸骨 + 金币 + 朱砂",
                "Craft: Emperor's Bone + Gold Coin + Cinnabar",
                "血肉骰：攻击 +20%、残血：攻击 +40%、连携·生死代价。",
                "Flesh Gamble Dice: attack +20%, attack +40% (at low health), synergy: Life for Power.",
                "dynasty:emperor_bone", "dynasty:gold_coin", "dynasty:cinnabar");
        entry(l, "folding_fan",
                "合成：符纸 + 竹简 + 丝绸",
                "Craft: Talisman Paper + Bamboo Slip + Silk",
                "折扇：移速 +6%、攻速 +8%。",
                "Folding Fan: movement speed +6%, attack speed +8%.",
                "dynasty:talisman_paper", "dynasty:bamboo_slip", "dynasty:silk");
        entry(l, "fox_spirit_pendant",
                "合成：九尾狐尾 + 玉 + 丝绸",
                "Craft: Fox Tail + Jade + Silk",
                "狐灵佩：移速 +12%、幸运 +2。",
                "Fox Spirit Pendant: movement speed +12%, luck +2.",
                "dynasty:fox_tail", "dynasty:jade", "dynasty:silk");
        entry(l, "ghost_ferry_tally",
                "合成：符纸 + 帝骸骨 + 朱砂",
                "Craft: Talisman Paper + Emperor's Bone + Cinnabar",
                "渡鬼符：攻速 +30%、常驻：生命上限 -25%、常驻内伤 I、命中斩杀 15% 血线以下的目标（60% 概率）、连携·幽冥献祭。",
                "Ghost Ferry Tally: attack speed +30%, max health -25% (always), permanent Internal Injury I, executes below 15% health (60% chance), synergy: Underworld Sacrifice.",
                "dynasty:talisman_paper", "dynasty:emperor_bone", "dynasty:cinnabar");
        entry(l, "gilded_lotus_crown",
                "合成：金币 + 金币 + 玉",
                "Craft: Gold Coin + Gold Coin + Jade",
                "金莲冠：攻击 +10%、移速 +5%。",
                "Gilded Lotus Crown: attack +10%, movement speed +5%.",
                "dynasty:gold_coin", "dynasty:gold_coin", "dynasty:jade");
        entry(l, "go_board",
                "合成：徽墨 + 玉 + 青铜锭",
                "Craft: Ink Stick + Jade + Bronze Ingot",
                "棋盘坠：攻速 +10%。",
                "Go Board Charm: attack speed +10%.",
                "dynasty:ink_stick", "dynasty:jade", "dynasty:bronze_ingot");
        entry(l, "golden_pill",
                "合成：长生丹 + 龙晶 + 金币",
                "Craft: Immortality Pill + Dragon Crystal + Gold Coin",
                "金丹：生命 +400、常驻再生 III。",
                "Golden Pill: health +400, permanent Regeneration III.",
                "dynasty:pill_longevity", "dynasty:dragon_crystal", "dynasty:gold_coin");
        entry(l, "guqin_string",
                "合成：丝绸 + 生丝",
                "Craft: Silk + Raw Silk",
                "古琴弦：攻速 +8%。",
                "Guqin String: attack speed +8%.",
                "dynasty:silk", "dynasty:raw_silk");
        entry(l, "guqin_tassel",
                "合成：丝绸 + 竹笛",
                "Craft: Silk + Bamboo Flute",
                "琴穗：攻速 +8%、生命 +120。",
                "Guqin Tassel: attack speed +8%, health +120.",
                "dynasty:silk", "dynasty:bamboo_flute");
        entry(l, "hawk_eye",
                "合成：玉 + 金币",
                "Craft: Jade + Gold Coin",
                "鹰眼：攻击 +10%、攻击距离 +2。",
                "Hawk Eye: attack +10%, attack range +2.",
                "dynasty:jade", "dynasty:gold_coin");
        entry(l, "horse_stirrup",
                "合成：青铜锭 + minecraft:leather",
                "Craft: Bronze Ingot + minecraft:leather",
                "马镫：骑乘：移速 +10%。",
                "Horse Stirrup: movement speed +10% (while mounted).",
                "dynasty:bronze_ingot", "minecraft:leather");
        entry(l, "immortal_crane_feather",
                "合成：凤凰羽 + 玉 + 丝绸",
                "Craft: Phoenix Feather + Jade + Silk",
                "仙鹤羽：移速 +12%、常驻缓降 I。",
                "Immortal Crane Feather: movement speed +12%, permanent Slow Falling I.",
                "dynasty:phoenix_feather", "dynasty:jade", "dynasty:silk");
        entry(l, "imperial_pearl_earring",
                "合成：避水珠 + 金币 + 丝绸",
                "Craft: Water-Repelling Pearl + Gold Coin + Silk",
                "东珠耳坠：生命 +200、幸运 +1。",
                "Imperial Pearl Earring: health +200, luck +1.",
                "dynasty:sea_pearl", "dynasty:gold_coin", "dynasty:silk");
        entry(l, "incense_sachet",
                "合成：朱砂 + 丝绸 + 锦缎",
                "Craft: Cinnabar + Silk + Brocade",
                "香囊：生命 +160、常驻再生 I。",
                "Incense Sachet: health +160, permanent Regeneration I.",
                "dynasty:cinnabar", "dynasty:silk", "dynasty:brocade");
        entry(l, "ink_slab_charm",
                "合成：玉 + 徽墨 + 丝绸",
                "Craft: Jade + Ink Stick + Silk",
                "砚台坠：幸运 +2、生命 +160。",
                "Ink Slab Charm: luck +2, health +160.",
                "dynasty:jade", "dynasty:ink_stick", "dynasty:silk");
        entry(l, "internal_injury_talisman",
                "合成：符纸 + 朱砂 + 雷部令",
                "Craft: Talisman Paper + Cinnabar + Thunder Token",
                "内伤符：攻击 +45%、常驻内伤 I、连携·生死代价。",
                "Internal Injury Talisman: attack +45%, permanent Internal Injury I, synergy: Life for Power.",
                "dynasty:talisman_paper", "dynasty:cinnabar", "dynasty:thunder_token");
        entry(l, "iron_helmet_plume",
                "合成：凤凰羽 + 精钢 + 丝绸",
                "Craft: Phoenix Feather + Refined Steel + Silk",
                "盔缨：护甲 +12、移速 +6%。",
                "Helmet Plume: armour +12, movement speed +6%.",
                "dynasty:phoenix_feather", "dynasty:refined_steel", "dynasty:silk");
        entry(l, "iron_pauldron",
                "合成：精钢 + 精钢",
                "Craft: Refined Steel + Refined Steel",
                "铁护肩：护甲 +14、攻击 +5%。",
                "Iron Pauldron: armour +14, attack +5%.",
                "dynasty:refined_steel", "dynasty:refined_steel");
        entry(l, "iron_ration_charm",
                "合成：竹简 + 丝绸 + 金币",
                "Craft: Bamboo Slip + Silk + Gold Coin",
                "军粮坠：生命 +350、攻速 -8%、连携·巧匠边塞。",
                "Iron Ration Charm: health +350, attack speed -8%, synergy: Frontier Craft.",
                "dynasty:bamboo_slip", "dynasty:silk", "dynasty:gold_coin");
        entry(l, "ivory_tusk",
                "合成：minecraft:bone + 银锭 + 玉",
                "Craft: minecraft:bone + Silver Ingot + Jade",
                "象牙：攻击距离 +2、攻击 +6%。",
                "Ivory Tusk: attack range +2, attack +6%.",
                "minecraft:bone", "dynasty:silver_ingot", "dynasty:jade");
        entry(l, "jade_belt_hook",
                "合成：玉 + 青铜锭",
                "Craft: Jade + Bronze Ingot",
                "玉带钩：护甲 +8、抗击退 +0.3。",
                "Jade Belt Hook: armour +8, knockback resistance +0.3.",
                "dynasty:jade", "dynasty:bronze_ingot");
        entry(l, "jade_bixie",
                "合成：玉 + 朱砂",
                "Craft: Jade + Cinnabar",
                "玉辟邪：击退 +0.4、攻击 +8%。",
                "Jade Bixie: attack knockback +0.4, attack +8%.",
                "dynasty:jade", "dynasty:cinnabar");
        entry(l, "jade_brush_holder",
                "合成：玉 + 竹简",
                "Craft: Jade + Bamboo Slip",
                "玉笔筒：攻速 +12%、攻击 +6%。",
                "Jade Brush Holder: attack speed +12%, attack +6%.",
                "dynasty:jade", "dynasty:bamboo_slip");
        entry(l, "jade_cong",
                "合成：玉 + dynasty:jade_block + 青铜锭",
                "Craft: Jade + dynasty:jade_block + Bronze Ingot",
                "玉琮：护甲 +12、抗击退 +0.4。",
                "Jade Cong: armour +12, knockback resistance +0.4.",
                "dynasty:jade", "dynasty:jade_block", "dynasty:bronze_ingot");
        entry(l, "jade_flying_apsara",
                "合成：玉 + 丝绸 + 金币",
                "Craft: Jade + Silk + Gold Coin",
                "玉飞天：移速 +8%、常驻缓降 I。",
                "Jade Apsara: movement speed +8%, permanent Slow Falling I.",
                "dynasty:jade", "dynasty:silk", "dynasty:gold_coin");
        entry(l, "jade_kylin",
                "合成：玉 + 麒麟角",
                "Craft: Jade + Qilin Horn",
                "玉麒麟：生命 +220、攻击 +10%。",
                "Jade Kylin: health +220, attack +10%.",
                "dynasty:jade", "dynasty:qilin_horn");
        entry(l, "jade_marrow_charm",
                "合成：玉 + 玉 + 丝绸",
                "Craft: Jade + Jade + Silk",
                "玉髓佩：生命 +180、护甲 +5。",
                "Jade Marrow Charm: health +180, armour +5.",
                "dynasty:jade", "dynasty:jade", "dynasty:silk");
        entry(l, "jade_ring",
                "合成：玉 + 丝绸",
                "Craft: Jade + Silk",
                "玉扳指：攻速 +10%、攻击距离 +1。",
                "Jade Ring: attack speed +10%, attack range +1.",
                "dynasty:jade", "dynasty:silk");
        entry(l, "jade_ruyi",
                "合成：玉 + dynasty:jade_block + 金币",
                "Craft: Jade + dynasty:jade_block + Gold Coin",
                "玉如意：幸运 +2、常驻幸运 I。",
                "Jade Ruyi: luck +2, permanent Luck I.",
                "dynasty:jade", "dynasty:jade_block", "dynasty:gold_coin");
        entry(l, "jade_shroud_charm",
                "合成：太乙玉 + 丝绸 + 帝骸骨",
                "Craft: Taiyi Jade + Silk + Emperor's Bone",
                "玉殓佩：生命 +400、移速 -10%、常驻内伤 I、连携·幽冥献祭。",
                "Jade Shroud Charm: health +400, movement speed -10%, permanent Internal Injury I, synergy: Underworld Sacrifice.",
                "dynasty:taiyi_jade", "dynasty:silk", "dynasty:emperor_bone");
        entry(l, "jade_silkworm",
                "合成：玉 + 生丝 + 丝绸",
                "Craft: Jade + Raw Silk + Silk",
                "玉蚕：残血：生命 +120、常驻生命恢复 II。",
                "Jade Silkworm: health +120 (at low health), permanent Regeneration II.",
                "dynasty:jade", "dynasty:raw_silk", "dynasty:silk");
        entry(l, "jade_zhang",
                "合成：玉 + dynasty:jade_block + 金币",
                "Craft: Jade + dynasty:jade_block + Gold Coin",
                "玉璋：攻击 +12%、攻速 +8%。",
                "Jade Zhang: attack +12%, attack speed +8%.",
                "dynasty:jade", "dynasty:jade_block", "dynasty:gold_coin");
        entry(l, "karma_ledger_charm",
                "合成：竹简 + 徽墨 + 朱砂",
                "Craft: Bamboo Slip + Ink Stick + Cinnabar",
                "因果牒：攻击 +30%、残血：护甲 +30、连携·幽冥献祭。",
                "Karma Ledger Charm: attack +30%, armour +30 (at low health), synergy: Underworld Sacrifice.",
                "dynasty:bamboo_slip", "dynasty:ink_stick", "dynasty:cinnabar");
        entry(l, "knee_guard",
                "合成：精钢 + minecraft:leather",
                "Craft: Refined Steel + minecraft:leather",
                "护膝：移速 +5%、抗击退 +0.2。",
                "Knee Guard: movement speed +5%, knockback resistance +0.2.",
                "dynasty:refined_steel", "minecraft:leather");
        entry(l, "leopard_tail",
                "合成：丝绸 + 生丝 + minecraft:bone",
                "Craft: Silk + Raw Silk + minecraft:bone",
                "豹尾：移速 +12%、攻速 +6%。",
                "Leopard Tail: movement speed +12%, attack speed +6%.",
                "dynasty:silk", "dynasty:raw_silk", "minecraft:bone");
        entry(l, "lifedrain_ring",
                "合成：帝骸骨 + 朱砂 + 玉",
                "Craft: Emperor's Bone + Cinnabar + Jade",
                "汲生戒：攻击 +30%、攻速 +10%、常驻内伤 II、命中吸血 12%、连携·生死代价。",
                "Lifedrain Ring: attack +30%, attack speed +10%, permanent Internal Injury II, 12% lifesteal on hit, synergy: Life for Power.",
                "dynasty:emperor_bone", "dynasty:cinnabar", "dynasty:jade");
        entry(l, "mandarin_rank_badge",
                "合成：丝绸 + 金币 + 朱砂",
                "Craft: Silk + Gold Coin + Cinnabar",
                "补子官徽：幸运 +2、生命 +180。",
                "Rank Badge: luck +2, health +180.",
                "dynasty:silk", "dynasty:gold_coin", "dynasty:cinnabar");
        entry(l, "mirror_pouch",
                "合成：铜镜 + 丝绸",
                "Craft: Bronze Mirror + Silk",
                "铜镜袋：护甲 +10、常驻抗性 I。",
                "Mirror Pouch: armour +10, permanent Resistance I.",
                "dynasty:bronze_mirror", "dynasty:silk");
        entry(l, "moonlit_mirror",
                "合成：铜镜 + 龙晶 + 丝绸",
                "Craft: Bronze Mirror + Dragon Crystal + Silk",
                "月华镜：夜晚：攻速 +14%、白天：幸运 +2、连携·昼夜双生。",
                "Moonlit Mirror: attack speed +14% (at night), luck +2 (in daylight), synergy: Day & Night.",
                "dynasty:bronze_mirror", "dynasty:dragon_crystal", "dynasty:silk");
        entry(l, "nether_binding_ring",
                "合成：帝骸骨 + 朱砂 + 龙晶",
                "Craft: Emperor's Bone + Cinnabar + Dragon Crystal",
                "幽冥缚戒：夜晚：攻击 +40%、白天：生命上限 -20%、命中附加 60 点雷罚（30% 概率）、连携·幽冥献祭。",
                "Nether Binding Ring: attack +40% (at night), max health -20% (in daylight), 60 extra thunder damage on hit (30% chance), synergy: Underworld Sacrifice.",
                "dynasty:emperor_bone", "dynasty:cinnabar", "dynasty:dragon_crystal");
        entry(l, "night_heron_feather",
                "合成：鹤羽 + 丝绸 + 金币",
                "Craft: Crane Feather + Silk + Gold Coin",
                "夜鹭羽：夜晚：攻击 +18%、击退 +0.35、命中满血目标 30%、连携·昼夜双生。",
                "Night Heron Feather: attack +18%, attack knockback +0.35 (at night), 30% against full-health targets, synergy: Day & Night.",
                "dynasty:crane_feather", "dynasty:silk", "dynasty:gold_coin");
        entry(l, "noon_pendant",
                "合成：玉 + 金币 + 丝绸",
                "Craft: Jade + Gold Coin + Silk",
                "正阳佩：白天：生命 +240、夜晚：生命 -160、连携·昼夜双生。",
                "Noon Pendant: health +240 (in daylight), health -160 (at night), synergy: Day & Night.",
                "dynasty:jade", "dynasty:gold_coin", "dynasty:silk");
        entry(l, "peach_sword",
                "合成：竹简 + 朱砂",
                "Craft: Bamboo Slip + Cinnabar",
                "桃木剑：攻击 +16%。",
                "Peach Wood Sword: attack +16%.",
                "dynasty:bamboo_slip", "dynasty:cinnabar");
        entry(l, "pearl_net_charm",
                "合成：避水珠 + 金币 + 丝绸",
                "Craft: Water-Repelling Pearl + Gold Coin + Silk",
                "珠网坠：生命 +200、幸运 +2。",
                "Pearl Net Charm: health +200, luck +2.",
                "dynasty:sea_pearl", "dynasty:gold_coin", "dynasty:silk");
        entry(l, "phoenix_hairpin",
                "合成：凤凰羽 + 金币 + 丝绸",
                "Craft: Phoenix Feather + Gold Coin + Silk",
                "凤钗：生命 +240、幸运 +1。",
                "Phoenix Hairpin: health +240, luck +1.",
                "dynasty:phoenix_feather", "dynasty:gold_coin", "dynasty:silk");
        entry(l, "phoenix_wing_charm",
                "合成：凤凰羽 + 凤凰羽 + 金币",
                "Craft: Phoenix Feather + Phoenix Feather + Gold Coin",
                "凤翼坠：移速 +10%、常驻缓降 I。",
                "Phoenix Wing Charm: movement speed +10%, permanent Slow Falling I.",
                "dynasty:phoenix_feather", "dynasty:phoenix_feather", "dynasty:gold_coin");
        entry(l, "pike_tassel",
                "合成：丝绸 + 精钢",
                "Craft: Silk + Refined Steel",
                "枪缨：攻击 +10%、攻击距离 +1。",
                "Pike Tassel: attack +10%, attack range +1.",
                "dynasty:silk", "dynasty:refined_steel");
        entry(l, "poem_scroll",
                "合成：符纸 + 徽墨 + 丝绸",
                "Craft: Talisman Paper + Ink Stick + Silk",
                "诗文卷轴：幸运 +2、常驻幸运 I。",
                "Poem Scroll: luck +2, permanent Luck I.",
                "dynasty:talisman_paper", "dynasty:ink_stick", "dynasty:silk");
        entry(l, "purple_qi_pearl",
                "合成：避水珠 + 玄天玉 + 龙晶",
                "Craft: Water-Repelling Pearl + Xuantian Jade + Dragon Crystal",
                "紫气珠：生命 +320、攻击 +14%。",
                "Purple Qi Pearl: health +320, attack +14%.",
                "dynasty:sea_pearl", "dynasty:xuantian_jade", "dynasty:dragon_crystal");
        entry(l, "qilin_hoof_charm",
                "合成：麒麟角 + 丝绸",
                "Craft: Qilin Horn + Silk",
                "麒麟蹄：生命 +260、攻速 +8%。",
                "Qilin Hoof Charm: health +260, attack speed +8%.",
                "dynasty:qilin_horn", "dynasty:silk");
        entry(l, "quickdraw_glove",
                "合成：丝绸 + 精钢 + 竹简",
                "Craft: Silk + Refined Steel + Bamboo Slip",
                "疾抽手套：攻速 +18%、击退 +0.6、连击每层 5%、连携·巧匠边塞。",
                "Quickdraw Glove: attack speed +18%, attack knockback +0.6, 5% per combo stack, synergy: Frontier Craft.",
                "dynasty:silk", "dynasty:refined_steel", "dynasty:bamboo_slip");
        entry(l, "rain_prayer_knot",
                "合成：丝绸 + 符纸 + 雷部令",
                "Craft: Silk + Talisman Paper + Thunder Token",
                "祈雨结：雷雨：攻速 +20%、攻击 +30%、连携·巧匠边塞。",
                "Rain Prayer Knot: attack speed +20%, attack +30% (in a thunderstorm), synergy: Frontier Craft.",
                "dynasty:silk", "dynasty:talisman_paper", "dynasty:thunder_token");
        entry(l, "ranging_compass_charm",
                "合成：铜镜 + 玉 + 精钢",
                "Craft: Bronze Mirror + Jade + Refined Steel",
                "望距罗盘：攻击距离 +2、攻击 +8%、连携·巧匠边塞。",
                "Ranging Compass Charm: attack range +2, attack +8%, synergy: Frontier Craft.",
                "dynasty:bronze_mirror", "dynasty:jade", "dynasty:refined_steel");
        entry(l, "rhino_horn",
                "合成：minecraft:bone + 精钢 + 玉",
                "Craft: minecraft:bone + Refined Steel + Jade",
                "犀角：攻击 +14%、护甲 +6。",
                "Rhino Horn: attack +14%, armour +6.",
                "minecraft:bone", "dynasty:refined_steel", "dynasty:jade");
        entry(l, "saber_tassel",
                "合成：丝绸 + 朱砂",
                "Craft: Silk + Cinnabar",
                "刀穗：攻击 +7%、攻速 +5%。",
                "Saber Tassel: attack +7%, attack speed +5%.",
                "dynasty:silk", "dynasty:cinnabar");
        entry(l, "sacrificial_blade_charm",
                "合成：帝骸骨 + 精钢 + 朱砂",
                "Craft: Emperor's Bone + Refined Steel + Cinnabar",
                "祭刃坠：攻击 +38%、常驻内伤 I、命中斩杀 18% 血线以下的目标（80% 概率）、连携·幽冥献祭。",
                "Sacrificial Blade Charm: attack +38%, permanent Internal Injury I, executes below 18% health (80% chance), synergy: Underworld Sacrifice.",
                "dynasty:emperor_bone", "dynasty:refined_steel", "dynasty:cinnabar");
        entry(l, "scale_plate",
                "合成：龙鳞 + 精钢",
                "Craft: Dragon Scale + Refined Steel",
                "甲片：护甲 +9、抗击退 +0.25。",
                "Scale Plate: armour +9, knockback resistance +0.25.",
                "dynasty:dragon_scale", "dynasty:refined_steel");
        entry(l, "scarlet_lotus",
                "合成：玉 + 朱砂 + 丝绸",
                "Craft: Jade + Cinnabar + Silk",
                "血莲：残血：护甲 +14、攻速 +15%、连携·生死代价。",
                "Scarlet Lotus: armour +14, attack speed +15% (at low health), synergy: Life for Power.",
                "dynasty:jade", "dynasty:cinnabar", "dynasty:silk");
        entry(l, "scholar_ink_badge",
                "合成：玉 + 朱砂 + 金币",
                "Craft: Jade + Cinnabar + Gold Coin",
                "墨玉印坠：生命 +180、幸运 +1。",
                "Scholar Ink Badge: health +180, luck +1.",
                "dynasty:jade", "dynasty:cinnabar", "dynasty:gold_coin");
        entry(l, "scroll_case_charm",
                "合成：竹简 + 徽墨 + 丝绸",
                "Craft: Bamboo Slip + Ink Stick + Silk",
                "书箱坠：攻速 +10%、幸运 +1。",
                "Scroll Case Charm: attack speed +10%, luck +1.",
                "dynasty:bamboo_slip", "dynasty:ink_stick", "dynasty:silk");
        entry(l, "seal_charm",
                "合成：官印 + 丝绸",
                "Craft: Official Seal + Silk",
                "印章坠：生命 +100、幸运 +1。",
                "Seal Charm: health +100, luck +1.",
                "dynasty:official_seal", "dynasty:silk");
        entry(l, "seal_of_two_heavens",
                "合成：混元珠 + 金币 + 兵器图纸",
                "Craft: Hunyuan Pearl + Gold Coin + Weapon Blueprint",
                "双天印：攻击 +12%、白天：移速 +6%、常驻龙威 I、连携·天朝敕令。",
                "Seal of Two Heavens: attack +12%, movement speed +6% (in daylight), permanent Dragon Might I, synergy: Imperial Edict.",
                "dynasty:hunyuan_pearl", "dynasty:gold_coin", "dynasty:blueprint");
        entry(l, "siege_hammer_charm",
                "合成：精钢 + 龙鳞 + 丝绸",
                "Craft: Refined Steel + Dragon Scale + Silk",
                "破阵锤坠：满血：攻击 +25%、命中斩杀 12% 血线以下的目标（80% 概率）、连携·巧匠边塞。",
                "Siege Hammer Charm: attack +25% (at full health), executes below 12% health (80% chance), synergy: Frontier Craft.",
                "dynasty:refined_steel", "dynasty:dragon_scale", "dynasty:silk");
        entry(l, "snake_gall",
                "合成：朱砂 + 金创药",
                "Craft: Cinnabar + Healing Salve",
                "蛇胆：水下：攻击 +10%。",
                "Snake Gall: attack +10% (underwater).",
                "dynasty:cinnabar", "dynasty:healing_salve");
        entry(l, "soul_candle_charm",
                "合成：帝骸骨 + 朱砂 + 符纸",
                "Craft: Emperor's Bone + Cinnabar + Talisman Paper",
                "命烛坠：生命上限 -25%、夜晚：攻击 +28%、命中吸血 10%（50% 概率）、连携·生死代价。",
                "Soul Candle Charm: max health -25%, attack +28% (at night), 10% lifesteal on hit (50% chance), synergy: Life for Power.",
                "dynasty:emperor_bone", "dynasty:cinnabar", "dynasty:talisman_paper");
        entry(l, "star_diagram_charm",
                "合成：龙晶 + 玉 + 朱砂",
                "Craft: Dragon Crystal + Jade + Cinnabar",
                "星图佩：幸运 +3、生命 +140。",
                "Star Chart Charm: luck +3, health +140.",
                "dynasty:dragon_crystal", "dynasty:jade", "dynasty:cinnabar");
        entry(l, "star_dial",
                "合成：星盘 + 玉 + 龙晶",
                "Craft: Astrolabe + Jade + Dragon Crystal",
                "星斗盘：攻击 +12%、攻速 +10%。",
                "Star Dial: attack +12%, attack speed +10%.",
                "dynasty:star_compass", "dynasty:jade", "dynasty:dragon_crystal");
        entry(l, "starless_night_ring",
                "合成：帝骸骨 + 玉 + 金币",
                "Craft: Emperor's Bone + Jade + Gold Coin",
                "无星夜戒：夜晚：生命 +220、夜晚：攻击 +16%、命中吸血 8%、连携·昼夜双生。",
                "Starless Night Ring: health +220 (at night), attack +16% (at night), 8% lifesteal on hit, synergy: Day & Night.",
                "dynasty:emperor_bone", "dynasty:jade", "dynasty:gold_coin");
        entry(l, "storm_anchor_charm",
                "合成：精钢 + 龙晶 + 避水珠",
                "Craft: Refined Steel + Dragon Crystal + Water-Repelling Pearl",
                "镇海锚坠：护甲 +20、击退 +0.5。",
                "Storm Anchor Charm: armour +20, attack knockback +0.5.",
                "dynasty:refined_steel", "dynasty:dragon_crystal", "dynasty:sea_pearl");
        entry(l, "sun_chaser_ring",
                "合成：金币 + 玉 + 朱砂",
                "Craft: Gold Coin + Jade + Cinnabar",
                "追阳戒：白天：移速 +12%、攻击 +10%、连携·昼夜双生。",
                "Sun Chaser Ring: movement speed +12%, attack +10% (in daylight), synergy: Day & Night.",
                "dynasty:gold_coin", "dynasty:jade", "dynasty:cinnabar");
        entry(l, "sword_tassel",
                "合成：丝绸 + 银锭",
                "Craft: Silk + Silver Ingot",
                "剑穗：攻击 +6%、攻击距离 +1。",
                "Sword Tassel: attack +6%, attack range +1.",
                "dynasty:silk", "dynasty:silver_ingot");
        entry(l, "talisman_pouch",
                "合成：符纸 + 符纸 + 丝绸",
                "Craft: Talisman Paper + Talisman Paper + Silk",
                "符纸包：幸运 +3、常驻幸运 I。",
                "Talisman Pouch: luck +3, permanent Luck I.",
                "dynasty:talisman_paper", "dynasty:talisman_paper", "dynasty:silk");
        entry(l, "tea_cup",
                "合成：玉 + 茶",
                "Craft: Jade + Tea",
                "茶盏：生命 +200、常驻生命恢复 II。",
                "Tea Cup: health +200, permanent Regeneration II.",
                "dynasty:jade", "dynasty:tea");
        entry(l, "throne_inheritance_charm",
                "合成：太乙玉 + 玉 + 金币",
                "Craft: Taiyi Jade + Jade + Gold Coin",
                "承天佩：生命 +260、常驻天命 I、连携·天朝敕令。",
                "Throne Inheritance Charm: health +260, permanent Mandate of Heaven I, synergy: Imperial Edict.",
                "dynasty:taiyi_jade", "dynasty:jade", "dynasty:gold_coin");
        entry(l, "thunder_seal_charm",
                "合成：符纸 + 雷部令 + 朱砂",
                "Craft: Talisman Paper + Thunder Token + Cinnabar",
                "雷印符：攻击 +14%、攻速 +10%。",
                "Thunder Seal Charm: attack +14%, attack speed +10%.",
                "dynasty:talisman_paper", "dynasty:thunder_token", "dynasty:cinnabar");
        entry(l, "tiangang_talisman",
                "合成：天将令 + 符纸 + 朱砂",
                "Craft: Sky Token + Talisman Paper + Cinnabar",
                "天罡符：攻击 +18%、抗击退 +0.4。",
                "Tiangang Talisman: attack +18%, knockback resistance +0.4.",
                "dynasty:sky_token", "dynasty:talisman_paper", "dynasty:cinnabar");
        entry(l, "tide_compass_charm",
                "合成：铜镜 + 龙晶 + 丝绸",
                "Craft: Bronze Mirror + Dragon Crystal + Silk",
                "潮信坠：攻击距离 +2、移速 +6%。",
                "Tide Compass Charm: attack range +2, movement speed +6%.",
                "dynasty:bronze_mirror", "dynasty:dragon_crystal", "dynasty:silk");
        entry(l, "tiger_claw",
                "合成：minecraft:bone + 精钢",
                "Craft: minecraft:bone + Refined Steel",
                "虎爪：攻击 +12%、击退 +0.4。",
                "Tiger Claw: attack +12%, attack knockback +0.4.",
                "minecraft:bone", "dynasty:refined_steel");
        entry(l, "tomb_warden_seal",
                "合成：帝骸骨 + 精钢 + 金币",
                "Craft: Emperor's Bone + Refined Steel + Gold Coin",
                "守陵印：护甲 +25、常驻内伤 I、连携·幽冥献祭。",
                "Tomb Warden Seal: armour +25, permanent Internal Injury I, synergy: Underworld Sacrifice.",
                "dynasty:emperor_bone", "dynasty:refined_steel", "dynasty:gold_coin");
        entry(l, "turtle_blood_charm",
                "合成：龙鳞 + 朱砂 + 丝绸",
                "Craft: Dragon Scale + Cinnabar + Silk",
                "龟血符：残血：生命 +300、护甲 +16、常驻抗性 I。",
                "Turtle Blood Charm: health +300, armour +16 (at low health), permanent Resistance I.",
                "dynasty:dragon_scale", "dynasty:cinnabar", "dynasty:silk");
        entry(l, "turtle_shell",
                "合成：minecraft:scute + 玉",
                "Craft: minecraft:scute + Jade",
                "龟甲：护甲 +16、抗击退 +0.5。",
                "Turtle Shell: armour +16, knockback resistance +0.5.",
                "minecraft:scute", "dynasty:jade");
        entry(l, "twilight_cicada",
                "合成：玉 + 丝绸 + 符纸",
                "Craft: Jade + Silk + Talisman Paper",
                "蝉蜕影：白天：抗击退 +0.4、夜晚：攻击距离 +1、连携·昼夜双生。",
                "Twilight Cicada: knockback resistance +0.4 (in daylight), attack range +1 (at night), synergy: Day & Night.",
                "dynasty:jade", "dynasty:silk", "dynasty:talisman_paper");
        entry(l, "unbroken_wall_charm",
                "合成：玄武壳 + 精钢 + 兵器图纸",
                "Craft: Xuanwu Shell + Refined Steel + Weapon Blueprint",
                "不倾之壁：抗击退 +0.5、常驻铁壁 II、连携·天朝敕令。",
                "Unbroken Wall Charm: knockback resistance +0.5, permanent Iron Wall II, synergy: Imperial Edict.",
                "dynasty:xuanwu_shell", "dynasty:refined_steel", "dynasty:blueprint");
        entry(l, "underworld_gate_key",
                "合成：帝骸骨 + 雷部令 + 符纸",
                "Craft: Emperor's Bone + Thunder Token + Talisman Paper",
                "鬼门钥：雷雨：攻击 +45%、命中附加 90 点雷罚（25% 概率）、连携·幽冥献祭。",
                "Underworld Gate Key: attack +45% (in a thunderstorm), 90 extra thunder damage on hit (25% chance), synergy: Underworld Sacrifice.",
                "dynasty:emperor_bone", "dynasty:thunder_token", "dynasty:talisman_paper");
        entry(l, "war_banner_charm",
                "合成：丝绸 + 竹简 + 精钢",
                "Craft: Silk + Bamboo Slip + Refined Steel",
                "战旗坠：攻击 +12%、攻速 +6%。",
                "War Banner Charm: attack +12%, attack speed +6%.",
                "dynasty:silk", "dynasty:bamboo_slip", "dynasty:refined_steel");
        entry(l, "war_deity_signet",
                "合成：青龙鳞 + 金币 + 兵器图纸",
                "Craft: Qinglong Scale + Gold Coin + Weapon Blueprint",
                "战神印：攻击 +15%、常驻龙威 II、命中 40% 会心（30% 概率）、连携·天朝敕令。",
                "War Deity Signet: attack +15%, permanent Dragon Might II, 40% critical on hit (30% chance), synergy: Imperial Edict.",
                "dynasty:qinglong_scale", "dynasty:gold_coin", "dynasty:blueprint");
        entry(l, "warlord_drum_charm",
                "合成：精钢 + 丝绸 + 龙晶",
                "Craft: Refined Steel + Silk + Dragon Crystal",
                "战鼓墩：满血：攻速 +12%、残血：攻击 +40%、连击每层 6%、连携·巧匠边塞。",
                "Warlord Drum Charm: attack speed +12% (at full health), attack +40% (at low health), 6% per combo stack, synergy: Frontier Craft.",
                "dynasty:refined_steel", "dynasty:silk", "dynasty:dragon_crystal");
        entry(l, "wine_gourd",
                "合成：美酒 + 玉",
                "Craft: Wine + Jade",
                "酒葫芦：生命 +240、击退 +0.3。",
                "Wine Gourd: health +240, attack knockback +0.3.",
                "dynasty:wine", "dynasty:jade");
        entry(l, "wound_binder_charm",
                "合成：丝绸 + 符纸 + 玉",
                "Craft: Silk + Talisman Paper + Jade",
                "绷带佩：残血：护甲 +25、攻速 +18%、连携·巧匠边塞。",
                "Wound Binder Charm: armour +25, attack speed +18% (at low health), synergy: Frontier Craft.",
                "dynasty:silk", "dynasty:talisman_paper", "dynasty:jade");
        entry(l, "wrist_guard",
                "合成：精钢 + 丝绸",
                "Craft: Refined Steel + Silk",
                "护腕：护甲 +10、抗击退 +0.3。",
                "Wrist Guard: armour +10, knockback resistance +0.3.",
                "dynasty:refined_steel", "dynasty:silk");
        entry(l, "zen_bead_string",
                "合成：玉 + 丝绸 + 金币",
                "Craft: Jade + Silk + Gold Coin",
                "禅珠串：残血：生命 +220、常驻生命恢复 II。",
                "Zen Bead String: health +220 (at low health), permanent Regeneration II.",
                "dynasty:jade", "dynasty:silk", "dynasty:gold_coin");
    }
}
