package com.dynasty;

/** Generated by gen_trinkets7.py; do not edit. */
final class DynastyAccessoryData {
    record Bonus(String school, String kind, double amount) {}
    static Bonus get(String id) {
        return switch (id) {
            case "pojun_ring" -> new Bonus("sword", "melee", 0.12);
            case "wuqu_sword_knot" -> new Bonus("sword", "melee", 0.2);
            case "baizhan_ring" -> new Bonus("sword", "melee", 0.28);
            case "qixing_sword_knot" -> new Bonus("sword", "melee", 0.36);
            case "xuanjia_clasp" -> new Bonus("guard", "melee", 0.1);
            case "shanyue_bracelet" -> new Bonus("guard", "none", 0);
            case "beichen_heartguard" -> new Bonus("guard", "melee", 0.24);
            case "xuanyue_armlet" -> new Bonus("guard", "toughness", 0.006);
            case "yanling_thumbring" -> new Bonus("archer", "arrow", 0.12);
            case "shenji_quiver" -> new Bonus("archer", "arrow", 0.18);
            case "guanri_thumbring" -> new Bonus("archer", "arrow", 0.28);
            case "zhuiri_quiver" -> new Bonus("archer", "arrow", 0.36);
            case "lingwen_pendant" -> new Bonus("talisman", "edict", 0.15);
            case "leibu_seal" -> new Bonus("talisman", "edict", 0.22);
            case "ziwei_talisman_chain" -> new Bonus("talisman", "edict", 0.32);
            case "taiqing_talisman_case" -> new Bonus("talisman", "edict", 0.4);
            case "wanjun_ring" -> new Bonus("sword", "melee", 0.44);
            case "tianheng_sword_knot" -> new Bonus("sword", "melee", 0.52);
            case "zhenhai_heartguard" -> new Bonus("guard", "melee", 0.38);
            case "buzhou_armlet" -> new Bonus("guard", "melee", 0.76);
            case "sheyue_thumbring" -> new Bonus("archer", "arrow", 0.44);
            case "jinwu_quiver" -> new Bonus("archer", "arrow", 0.52);
            case "sanqing_talisman_chain" -> new Bonus("talisman", "edict", 0.48);
            case "yuxu_talisman_case" -> new Bonus("talisman", "edict", 0.56);
            default -> null;
        };
    }
}
